# Generated by Django 4.0.5 on 2022-08-02 11:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_intro', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "Приветствие". Не может быть пустым. Класс для [em] элемента "em"', verbose_name='Полный текст "Приветствие"')),
                ('blog_about', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "О блоге". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "О блоге"')),
                ('blog_goals', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "Наша цель". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "Наша цель"')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'О блоге',
                'verbose_name_plural': 'О блоге',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории. Не может быть пустым. Максимальное количество символов 50.', max_length=50, verbose_name='Категория')),
                ('number', models.PositiveIntegerField(default=0, help_text='Номер нужен для сортировки. Например, если значение [0] категория будет отображаться первым в списке.', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, null=True)),
                ('title', models.CharField(help_text='Название темы. Не может быть пустым. Максимальное количество символов 30.', max_length=30, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи. Не может быть пустым. Максимальное количество символов 500.', max_length=500, verbose_name='Заголовок')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Главное изображению')),
                ('main_image_caption', models.CharField(blank=True, help_text='Максимальное количество символов 500.', max_length=500, null=True, verbose_name='Подпись к изображению')),
                ('brief', models.TextField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Краткое описание')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Полный текст статьи')),
                ('draft', models.BooleanField(default=False, help_text='Отметить как черновик. Не будет показываться пользователям.', verbose_name='Черновик')),
                ('main', models.BooleanField(default=False, help_text='Отметить как основную статью на главной странице.', verbose_name='Освновная статья')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Категория')),
                ('themes', models.ManyToManyField(to='posts.theme', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
    ]
