# Generated by Django 4.0.5 on 2022-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи. Не может быть пустым. Максимальное количество символов 500.', max_length=500, verbose_name='Заголовок')),
                ('brief', models.CharField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Краткое описание')),
                ('full_content', models.TextField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Полный текст статьи')),
                ('verified', models.BooleanField(default=False, help_text='Отметить как черновик. Не будет показываться пользователям.', verbose_name='Черновик')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статьи',
                'ordering': ['-created'],
            },
        ),
    ]
