# Generated by Django 4.0.5 on 2022-06-24 07:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_theme_alter_post_options_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
