# Generated by Django 4.0.5 on 2022-06-24 09:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image_caption',
            field=models.CharField(blank=True, help_text='Максимальное количество символов 500.', max_length=500, null=True, verbose_name='Подпись к изображению'),
        ),
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Полный текст статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Главное изображению'),
        ),
    ]
