# Generated by Django 4.0.5 on 2022-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_main_image_caption_alter_post_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
