# Generated by Django 4.0.5 on 2022-06-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_slug_theme_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='verified',
            new_name='draft',
        ),
        migrations.AddField(
            model_name='post',
            name='themes',
            field=models.ManyToManyField(to='posts.theme', verbose_name='Темы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Главное изображению'),
        ),
    ]
