# Generated by Django 4.0.5 on 2022-06-28 06:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='blog_intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Приветствие', help_text='Полный текст "Приветствие". Не может быть пустым. Класс для [em] элемента "em"', verbose_name='Полный текст "Приветствие"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='blog_about',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "О блоге". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "О блоге"'),
        ),
        migrations.AlterField(
            model_name='about',
            name='blog_goals',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "Наша цель". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "Наша цель"'),
        ),
    ]
