# Generated by Django 4.0.5 on 2022-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_about_blog_intro_alter_about_blog_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.BooleanField(default=False, help_text='Отметить как основную статью на главной странице.', verbose_name='Освновная статья'),
        ),
    ]
