# Generated by Django 4.0.5 on 2022-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brief',
            field=models.TextField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Краткое описание'),
        ),
    ]
