# Generated by Django 4.0.5 on 2022-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['number'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Номер нужен для сортировки. Например, если значение [0] категория будет отображаться первым в списке.', verbose_name='Порядковый номер'),
        ),
    ]
