# Generated by Django 4.0.5 on 2022-08-02 11:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_intro', ckeditor_uploader.fields.RichTextUploadingField(help_text='"Саломлашиш" тўлиқ матни. Бўш бўлиши мумкин эмас. [em] элементи учун класс номи "em"', verbose_name='"Салом" тўлиқ матни')),
                ('blog_about', ckeditor_uploader.fields.RichTextUploadingField(help_text='"Блог ҳақида" тўлиқ матни. Бўш бўлиши мумкин эмас. [p] элементи учун класс номи "about-text"', verbose_name='"Блог ҳақида" тўлиқ матни')),
                ('blog_goals', ckeditor_uploader.fields.RichTextUploadingField(help_text='"Бизнинг мақсадимиз". тўлиқ матни. Бўш бўлиши мумкин эмас. [p] элементи учун класс номи "about-text"', verbose_name='"Бизнинг мақсадимиз" тўлиқ матни')),
                ('created', models.DateTimeField(verbose_name='Яратилди')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блог ҳақида',
                'verbose_name_plural': 'Блог ҳақида',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CategoryUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Категория номи. Бўш бўлиши мумкин эмас. Белгиларнинг максимал сони 50.', max_length=50, verbose_name='Категория')),
                ('number', models.PositiveIntegerField(default=0, help_text='Рақам саралаш учун керак. Мисол учун, агар қиймат [0] бўлса, тоифа рўйхатда биринчи бўлиб кўрсатилади.', verbose_name='Тартиб рақами')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ThemeUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, null=True)),
                ('title', models.CharField(help_text='Мавзу номи. Бўш бўлиши мумкин эмас. Белгиларнинг максимал сони 30.', max_length=30, verbose_name='Мавзу')),
            ],
            options={
                'verbose_name': 'Мавзу',
                'verbose_name_plural': 'Мавзулар',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PostUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи. Не может быть пустым. Максимальное количество символов 500.', max_length=500, verbose_name='Мақоланинг сарлавҳаси')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Асосий расм')),
                ('main_image_caption', models.CharField(blank=True, help_text='Максимальное количество символов 500.', max_length=500, null=True, verbose_name='Асосий расмга изоҳ')),
                ('brief', models.TextField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Мақоланиниг қисқа матн')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Мақоланинг тўлиқ матни')),
                ('draft', models.BooleanField(default=False, help_text='Отметить как черновик. Не будет показываться пользователям.', verbose_name='Қоралама')),
                ('main', models.BooleanField(default=False, help_text='Отметить как основную статью на главной странице.', verbose_name='Асосий мақола')),
                ('created', models.DateTimeField(verbose_name='Яратилган вақт')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='postsuz.categoryuz', verbose_name='Категория')),
                ('themes', models.ManyToManyField(to='postsuz.themeuz', verbose_name='Мавзулар')),
            ],
            options={
                'verbose_name': 'Мақола',
                'verbose_name_plural': 'Мақолалар',
                'ordering': ['-created'],
            },
        ),
    ]
