# Generated by Django 4.0.5 on 2022-07-19 19:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0012_alter_post_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_intro', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "Приветствие". Не может быть пустым. Класс для [em] элемента "em"', verbose_name='Полный текст "Приветствие"')),
                ('blog_about', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "О блоге". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "О блоге"')),
                ('blog_goals', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст "Наша цель". Не может быть пустым. Класс для [p] элемента "about-text"', verbose_name='Полный текст "Наша цель"')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'О блоге',
                'verbose_name_plural': 'О блоге',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи. Не может быть пустым. Максимальное количество символов 500.', max_length=500, verbose_name='Мақоланинг сарлавҳаси')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Асосий расм')),
                ('main_image_caption', models.CharField(blank=True, help_text='Максимальное количество символов 500.', max_length=500, null=True, verbose_name='Асосий расмга изоҳ')),
                ('brief', models.TextField(blank=True, help_text='Краткое описание статьи. Будет показыватсья в списках вместе с картинкой. Максимальное количество символов 500.', max_length=2000, null=True, verbose_name='Мақоланиниг қисқа матн')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Мақоланинг тўлиқ матни')),
                ('draft', models.BooleanField(default=False, help_text='Отметить как черновик. Не будет показываться пользователям.', verbose_name='Қоралама')),
                ('main', models.BooleanField(default=False, help_text='Отметить как основную статью на главной странице.', verbose_name='Асосий мақола')),
                ('created', models.DateTimeField(verbose_name='Яратилган вақт')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Категория')),
                ('themes', models.ManyToManyField(to='posts.theme', verbose_name='Мавзулар')),
            ],
            options={
                'verbose_name': 'Мақола',
                'verbose_name_plural': 'Мақолалар',
                'ordering': ['-created'],
            },
        ),
    ]
