# Generated by Django 4.0.5 on 2022-06-28 08:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Ссылка на страницу. Не может быть пустым. Максимальное количество символов 100.', max_length=100, verbose_name='Ссылка на страницу')),
                ('title', models.CharField(help_text='Заголовок страницы. Не может быть пустым. Максимальное количество символов 500.', max_length=500, verbose_name='Заголовок')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Полный текст статьи. Не может быть пустым. Максимальное количество символов не ограничено.', verbose_name='Полный текст статьи')),
                ('draft', models.BooleanField(default=False, help_text='Отметить как черновик. Не будет показываться пользователям.', verbose_name='Черновик')),
                ('created', models.DateTimeField(verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-created'],
            },
        ),
    ]
