# Generated by Django 4.0.5 on 2022-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
