# Generated by Django 4.0.5 on 2022-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Показать'),
        ),
    ]
